version: '3.3'

services:
    web: 
        build: .
        command: mix phx.server
        ports:
            - "4000:4000"
        volumes: 
            - .:/awesome
        depends_on:
            - db
    db:
        image: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: default_db